version: '3.0'

networks:
  default:
    external:
      name: mysterious-network

services:
  mysterious-mysql:
    container_name: mysterious-mysql
    image: 100zz/test-mysql:${MYSQL_VERSION}
    restart: always
    command: --max-connections=1000 --slow_query_log=1 --slow_query_log_file=/var/lib/mysql/slow-log.log --long_query_time=1
    volumes:
      - /opt/mysterious/mysql/data:/var/lib/mysql
      - /opt/mysterious/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Test@123456
      MYSQL_DATABASE: mysterious
      TZ: Asia/Shanghai
    ports:
      - "23306:3306"

  mysterious-redis:
    container_name: mysterious-redis
    image: 100zz/test-redis:${REDIS_VERSION}
    restart: always
    volumes:
      - redis_data:/data
      - redis_conf:/etc/redis
    sysctls:
      - net.core.somaxconn=1024
    ports:
      - "16379:6379"
    command: >  # 注意多个命令时的写法
      bash -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && redis-server /etc/redis/redis.conf"

  mysterious-nginx:
    container_name: mysterious-nginx
    image: 100zz/test-nginx:${NGINX_VERSION}
    restart: always
    volumes:
      - /opt/mysterious/nginx/conf.d:/etc/nginx/conf.d
      - /opt/mysterious/nginx/html:/usr/share/nginx/html
    ports:
      - "1234:1234"

  mysterious:
    container_name: mysterious
    image: 100zz/mysterious:${MYSTERIOUS_VERSION}
    restart: always
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: -Xmx4g -Xms4g
    volumes:
      - /opt/mysterious/logs:/root/logs
    ports:
      - "4321:4321"
    depends_on:
      - mysterious-mysql