version: '3.0'

services:
  mysterious-mysql:
    container_name: mysterious-mysql
    image: 100zz/test-mysql:${MYSQL_VERSION}
    restart: always
    command: --max-connections=1000 --slow_query_log=1 --slow_query_log_file=/var/lib/mysql/slow-log.log --long_query_time=1
    volumes:
      - /opt/mysterious/mysql/data:/var/lib/mysql
      - /opt/mysterious/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Test@123456
      MYSQL_DATABASE: mysterious
      TZ: Asia/Shanghai
      LANG: C.UTF-8
    ports:
      - "23306:3306"

  mysterious-redis:
    container_name: mysterious-redis
    image: 100zz/test-redis:${REDIS_VERSION}
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/mysterious/redis/data:/data
      - /opt/mysterious/redis/logs:/logs
      - /opt/mysterious/redis/conf/redis.conf:/etc/redis/redis.conf
    sysctls:
      - net.core.somaxconn=1024
    ports:
      - "16379:6379"
    privileged: true
    command: >  # 注意多个命令时的写法
      bash -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && redis-server /etc/redis/redis.conf"

  mysterious-nginx:
    container_name: mysterious-nginx
    image: 100zz/test-nginx:${NGINX_VERSION}
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/mysterious/nginx/conf.d:/etc/nginx/conf.d
      - /opt/mysterious/nginx/html:/usr/share/nginx/html
    ports:
      - "1234:1234"
      - "9998:9998"

  mysterious:
    container_name: mysterious
    image: 100zz/mysterious:${MYSTERIOUS_VERSION}
    restart: always
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: -Xmx4g -Xms4g
    volumes:
      - /opt/mysterious/logs:/opt/logs
      - /opt/mysterious/mysterious-jmeter:/opt/mysterious/mysterious-jmeter
      - /opt/mysterious/mysterious-data:/opt/mysterious/mysterious-data
    ports:
      - "4321:4321"
    depends_on:
      - mysterious-mysql
      - mysterious-nginx
      - mysterious-redis