apiVersion: 1
datasources:
  - name: InfluxDB-JMeter
    type: influxdb
    access: proxy
    url: http://mysterious-influxdb:8086
    isDefault: true
    database: jmeter
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      httpMode: POST
      timeInterval: "5s"
